---
- name: Setup synlogy NAS
  hosts: all
  become: yes
  roles:
    - docker
    - telegraf
    # tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
