---
- name: Setup synlogy NAS
  hosts: all
  become: true
  roles:
    - python
    - docker
    - telegraf
    - freshrss
    - grafana
    - influxdb
    # tasks:
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
