---
- name: Create a volume
  community.docker.docker_volume:
    name: caddy

# copy config file to the volume
- name: Start a container
  community.docker.docker_container:
    name: container
    image: alpine
    detach: no
    volumes:
      - caddy:/data

- name: Copy over the config
  template: src=Caddyfile dest=/tmp/Caddyfile

- name: Copy into the container
  command: /usr/local/bin/docker cp /tmp/Caddyfile container:/data/

- name: Remove the hanging container
  community.docker.docker_container:
    name: container
    image: alpine
    state: absent

- name: Caddy container
  community.docker.docker_container:
    name: caddy
    image: manojm321/caddy:v2
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    log_driver: "json-file"
    log_options: "max-size=10m"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "caddy:/data"
    network_mode: default
    networks:
      - name: macvlan
        ipv4_address: "{{ macvlan_ip_caddy }}"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
      - "2020:2020"
    command: caddy run --watch --config /data/Caddyfile --adapter caddyfile

- name: collect metrics
  ansible.builtin.template:
    src: "telegraf-caddy-output.conf"
    dest: "/etc/telegraf/telegraf.d/telegraf-caddy-output.conf"
    mode: 0644
  notify:
    - reload telegraf
  tags: metric
