---
- include: install.yaml
- include: setup-user.yaml
- include: install-speedtest-cli.yaml

- name: Copy config file
  ansible.builtin.copy:
    src: "telegraf.conf"
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644
  notify:
    - reload telegraf

- name: Copy output plugin config file
  ansible.builtin.template:
    src: "influxdb-output.conf"
    dest: "/etc/telegraf/telegraf.d/influxdb-output.conf"
    mode: 0644
  notify:
    - reload telegraf
