---
- name: Create a volume
  community.docker.docker_volume:
    name: pihole-data

- name: Create a volume
  community.docker.docker_volume:
    name: pihole-dnsmasq

- name: Pi-hole container
  community.docker.docker_container:
    name: pihole
    image: "pihole/pihole"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    log_driver: "json-file"
    log_options: "max-size=10m"
    capabilities: 'NET_ADMIN'
    volumes:
      - "pihole-data:/etc/pihole/"
      - "pihole-dnsmasq:/etc/dnsmasq.d/"
    network_mode: default
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    env:
      TZ: "America/Los_Angeles"
      WEBPASSWORD: "{{ pihole_webadmin_pass }}"
      ServerIP: "{{ macvlan_ip_pihole }}"
      DNSMASQ_LISTENING: local
    networks:
      - name: macvlan
        ipv4_address: "{{ macvlan_ip_pihole }}"
    dns_servers:
      - 127.0.0.1
      - 8.8.8.8

- name: Copy telegraf config file
  ansible.builtin.template:
    src: "telegraf-pihole.conf"
    dest: "/etc/telegraf/telegraf.d/telegraf-pihole.conf"
    mode: 0644
  notify:
    - reload telegraf
